// <auto-generated />
using System;
using BusBookingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusBookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusBookingSystem.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BusBookingSystem.Domain.Entities.Bus", b =>
                {
                    b.Property<string>("BusNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BusNumber");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            BusNumber = "BUS001",
                            Capacity = 50,
                            IsActive = true,
                            Route = "City Center - Airport"
                        },
                        new
                        {
                            BusNumber = "BUS002",
                            Capacity = 45,
                            IsActive = true,
                            Route = "North Station - South Station"
                        },
                        new
                        {
                            BusNumber = "BUS003",
                            Capacity = 40,
                            IsActive = true,
                            Route = "East Terminal - West Terminal"
                        },
                        new
                        {
                            BusNumber = "BUS004",
                            Capacity = 35,
                            IsActive = true,
                            Route = "Shopping Mall - University"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
